CREATE DATABASE insurance_company

CREATE TABLE `policies` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `company` varchar(255) NOT NULL,
  `price` varchar(255) NOT NULL,
  `type_image_url` varchar(255) NOT NULL,
  `company_image_url` varchar(255) NOT NULL,
  `insurance_details` text NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


INSERT INTO `policies` (`id`, `name`, `description`, `company`, `price`, `type_image_url`, `company_image_url`, `insurance_details`, `created_at`, `updated_at`) VALUES
(1, 'Car Insurance', 'Covers all damages to your vehicle.', 'ABC Insurance', '1200 USD', 'https://buyfromturkey.co/wp-content/uploads/2022/04/allaboutcarinsurance3.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHOGu099kSqCA2KKwj4vkRwPhM941Dlfz9bglg-8mqoCV-G_SdmzDMJKT30M0p28E7gj4&usqp=CAU', 'Covers damages to your car caused by accidents, theft, natural disasters, and other incidents. The policy may also include coverage for medical expenses related to accidents, third-party liabilities, and vehicle depreciation. Additional services such as roadside assistance may also be available.', NULL, NULL),
(2, 'Health Insurance', 'Covers all medical expenses during hospitalization.', 'XYZ Insurance', '2500 USD', 'https://today.uconn.edu/wp-content/uploads/2017/04/shutterstock_373492012-health-insurance-e1491415000969.jpg', 'https://i.pinimg.com/736x/53/6e/f7/536ef704d35845627b5667480b6a09b9.jpg', 'This policy covers hospitalization costs, medical treatments, surgeries, doctor’s fees, and prescription medications. It also provides coverage for emergency medical services and outpatient treatments. With this policy, you gain access to comprehensive healthcare, ensuring your medical needs are covered.', NULL, NULL),
(3, 'Home Insurance', 'Provides protection for your home against disasters and theft.', 'DEF Insurance', '800 USD', 'https://www.thebusinessscroll.com/wp-content/uploads/2024/04/Home-Insurance.webp', 'https://static.vecteezy.com/system/resources/previews/015/580/417/non_2x/def-letter-logo-design-on-white-background-def-creative-initials-letter-logo-concept-def-letter-design-vector.jpg', 'Provides coverage for damages to your property caused by natural disasters (earthquakes, floods, etc.), theft, fire, and other incidents. It also covers repair costs for any damages to the structure of the house and its contents, including personal belongings and furniture.', NULL, NULL),
(4, 'Travel Insurance', 'Covers all risks during your travel, including cancellations and delays.', 'GHI Insurance', '600 USD', 'https://yourtravelandhealth.com/wp-content/uploads/2023/05/Travel-insurance-featured-image-e1684353975541-1.webp', 'https://thumbs.dreamstime.com/b/exclusive-logo-features-elements-letter-ghi-monogram-design-simple-modern-minimal-style-crafted-to-work-329037854.jpg', 'This travel insurance includes coverage for flight cancellations, delays, lost luggage, and other travel-related risks. It also offers emergency medical assistance and coverage for medical treatment during your trip. In the event of a medical emergency, it may also provide coverage for your return trip or accommodation changes.', NULL, NULL),
(5, 'Life Insurance', 'Pays a sum to your beneficiaries in the event of your death.', 'ABC Insurance', '1500 USD', 'https://media.geeksforgeeks.org/wp-content/cdn-uploads/20221223125246/LIFE-INSURANCE-2.png', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHOGu099kSqCA2KKwj4vkRwPhM941Dlfz9bglg-8mqoCV-G_SdmzDMJKT30M0p28E7gj4&usqp=CAU', 'This life insurance policy guarantees a payout to your beneficiaries in case of your death. It may also include coverage for accidental death or disability. The sum paid can help your family cover expenses such as funeral costs, outstanding debts, and living expenses.\r\n', NULL, NULL),
(6, 'Business Insurance', 'Covers damage to your business property from fire, theft, etc.', 'DEF Insurance', '2000 USD', 'https://cdn.prod.website-files.com/61d8bd8e7dfa2dd9aba11ff0/636a78fb9af0169307e35323_What%20Is%20The%20Most%20Common%20Business%20Insurance.jpg', 'https://static.vecteezy.com/system/resources/previews/015/580/417/non_2x/def-letter-logo-design-on-white-background-def-creative-initials-letter-logo-concept-def-letter-design-vector.jpg', 'This policy offers coverage for damage to your business property due to fires, theft, vandalism, and natural disasters. It can also include coverage for lost income if your business is temporarily closed due to damages, as well as liability insurance for any accidents or injuries on your business premises.', NULL, NULL),
(7, 'Car Insurance', 'Covers all damages to your vehicle.', 'XYZ Insurance', '1000 USD', 'https://buyfromturkey.co/wp-content/uploads/2022/04/allaboutcarinsurance3.jpg', 'https://i.pinimg.com/736x/53/6e/f7/536ef704d35845627b5667480b6a09b9.jpg', 'This car insurance policy covers damages to your vehicle caused by accidents, theft, fire, and other types of damage. The policy may also provide coverage for medical costs, repairs, and third-party liabilities.', NULL, NULL),
(8, 'Health Insurance', 'Covers all medical expenses during hospitalization.', 'DEF Insurance', '2300 USD', 'https://today.uconn.edu/wp-content/uploads/2017/04/shutterstock_373492012-health-insurance-e1491415000969.jpg', 'https://static.vecteezy.com/system/resources/previews/015/580/417/non_2x/def-letter-logo-design-on-white-background-def-creative-initials-letter-logo-concept-def-letter-design-vector.jpg', 'Covers the full range of healthcare needs, including inpatient and outpatient treatments, surgeries, doctor consultations, and prescription medications. Some plans may offer extra coverage for dental or vision care, and rehabilitation services.', NULL, NULL),
(9, 'Life Insurance', 'Pays a sum to your beneficiaries in the event of your death.', 'GHI Insurance', '1500 USD', 'https://media.geeksforgeeks.org/wp-content/cdn-uploads/20221223125246/LIFE-INSURANCE-2.png', 'https://thumbs.dreamstime.com/b/exclusive-logo-features-elements-letter-ghi-monogram-design-simple-modern-minimal-style-crafted-to-work-329037854.jpg', 'Provides a death benefit to your beneficiaries in the event of your passing, offering financial support to cover living expenses, debts, and future needs. Some policies may offer options for additional coverage for critical illnesses or total disability.\r\n', NULL, NULL),
(10, 'Health Insurance', 'Covers all medical expenses during hospitalization.', 'ABC Insurance', '750 USD', 'https://today.uconn.edu/wp-content/uploads/2017/04/shutterstock_373492012-health-insurance-e1491415000969.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHOGu099kSqCA2KKwj4vkRwPhM941Dlfz9bglg-8mqoCV-G_SdmzDMJKT30M0p28E7gj4&usqp=CAU', 'This basic health insurance covers essential medical services, including hospitalization, outpatient care, and surgeries. It may also cover medical emergencies, offering financial support for unexpected medical costs during illness or accidents.', NULL, NULL);
